# ==============================================================================
# netlify.toml
#
# Este archivo configura el proceso de construcción y despliegue en Netlify.
# Define el directorio base del proyecto, el comando de construcción, el directorio
# de publicación, la ubicación de las funciones serverless y las reglas de
# redirección para una aplicación de una sola página (SPA).
#
# ==============================================================================

# [build] section:
# Configura las opciones de construcción.
[build]
  # 'base' especifica el subdirectorio donde se encuentra el proyecto.
  # Netlify ejecutará los comandos de construcción desde este directorio.
  base = "transparencia-conectada"

  # 'publish' define el directorio que Netlify debe publicar después de la
  # construcción. Este es el resultado del comando 'npm run build'.
  publish = "dist"

  # 'command' es el script que Netlify ejecutará para construir tu proyecto.
  command = "npm run build"

# [functions] section:
# Configura el directorio donde se encuentran las funciones serverless de Netlify.
[functions]
  # 'directory' especifica la ruta a la carpeta que contiene las funciones.
  # Es importante que el comando de construcción las compile a este lugar.
  directory = "dist/netlify/funciones"

# [[redirects]] section:
# Configura las reglas de redirección.
# Este bloque es esencial para las aplicaciones de una sola página (SPA)
# como las de Vite. Redirige todas las solicitudes de rutas no existentes
# al archivo 'index.html', permitiendo que el enrutador de tu aplicación
# maneje la navegación.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [dev] section:
# Configura opciones para el servidor de desarrollo local de Netlify (netlify dev).
[dev]
  # 'command' es el script que se ejecuta al usar 'netlify dev'.
  command = "npm run dev"
  
  # 'port' define el puerto para el servidor local.
  port = 5173# ==============================================================================
# netlify.toml
#
# Este archivo configura el proceso de construcción y despliegue en Netlify.
# Define el directorio base del proyecto, el comando de construcción, el directorio
# de publicación, la ubicación de las funciones serverless y las reglas de
# redirección para una aplicación de una sola página (SPA).
#
# ==============================================================================

# [build] section:
# Configura las opciones de construcción.
[build]
  # 'base' especifica el subdirectorio donde se encuentra el proyecto.
  # Netlify ejecutará los comandos de construcción desde este directorio.
  base = "transparencia-conectada"

  # 'publish' define el directorio que Netlify debe publicar después de la
  # construcción. Este es el resultado del comando 'npm run build'.
  publish = "dist"

  # 'command' es el script que Netlify ejecutará para construir tu proyecto.
  command = "npm run build"

# [functions] section:
# Configura el directorio donde se encuentran las funciones serverless de Netlify.
[functions]
  # 'directory' especifica la ruta a la carpeta que contiene las funciones.
  # Es importante que el comando de construcción las compile a este lugar.
  directory = "dist/netlify/funciones"

# [[redirects]] section:
# Configura las reglas de redirección.
# Este bloque es esencial para las aplicaciones de una sola página (SPA)
# como las de Vite. Redirige todas las solicitudes de rutas no existentes
# al archivo 'index.html', permitiendo que el enrutador de tu aplicación
# maneje la navegación.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [dev] section:
# Configura opciones para el servidor de desarrollo local de Netlify (netlify dev).
[dev]
  # 'command' es el script que se ejecuta al usar 'netlify dev'.
  command = "npm run dev"
  
  # 'port' define el puerto para el servidor local.
  port = 5173