# Configuraci칩n de despliegue para Netlify

[build]
  # Comando para construir el sitio
  command = "npm run build"
  
  # Directorio que Netlify desplegar치
  publish = "dist"

[dev]
  # Comando para el entorno de desarrollo local
  command = "npm run dev"
  
  # Puerto para el servidor de desarrollo
  port = 5173

# Regla de redirecci칩n para aplicaciones de una sola p치gina (SPA)
# Esto asegura que todas las rutas sean manejadas por index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
